config/routes.rb
Rails.application.routes.draw do
  get 'mail_stores/template'

  devise_for :users, controllers: {
                       sessions: 'users/sessions',
                       passwords: 'users/passwords',
                       registrations: 'users/registrations',
                       unlocks: 'users/unlocks',
                       confirmations: 'users/confirmations',
                       invitations: 'users/invitations'
                   }
  get 'home/index'
  get :email_open, to: 'home#email_open'

  root 'home#index'

  resources :mail_stores
  resources :campaigns do
    resources :recipients do
      get :open
    end
    get :email_view
    post :publish
  end

  namespace :webhook do
    post :delivered, to: 'email_campaign#delivered'
    post :opened, to: 'email_campaign#opened'
    post :clicked, to: 'email_campaign#clicked'
    post :bounced, to: 'email_campaign#bounced'
    post :spamed, to: 'email_campaign#spamed'
  end

  resources :social_campaigns do
    get :share, on: :member
  end

end

app/views/shared/_main_nav.html.erb
<div class="side-menu-wrapper">
  <div class="nav-side-menu">
    <div class="brand">
      <%= image_tag('syftet-logo.png') %>
    </div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>

    <div class="menu-list">
      <ul id="menu-content" class="menu-content collapse out">
        <li>
          <a href="<%= root_path %>">
            <i class="fa fa-dashboard fa-lg"></i> Dashboard
          </a>
        </li>
        <li data-toggle="collapse" data-target="#campaign" class="collapsed">
          <a href="javascript:void(0)">
            <i class="fa fa-envelope fa-lg"></i> Campaign <span class="arrow"></span>
          </a>
        </li>
        <ul class="sub-menu collapse <%= active_collapse(['campaigns', 'recipients']) %>" id="campaign">
          <li>
            <%= link_to 'New Campaign', new_campaign_path %>
          </li>
          <li>
            <%= link_to 'Campaign Lists', campaigns_path %>
          </li>
          <li>
            <%= link_to 'Stats', campaigns_path %>
          </li>
        </ul>
        <li data-toggle="collapse" data-target="#events" class="collapsed">
          <a href="javascript:void(0)">
            <i class="fa fa-calendar fa-lg"></i> Events <span class="arrow"></span>
          </a>
        </li>
        <ul class="sub-menu collapse <%= active_collapse(['events']) %>" id="events">
          <li>
            <%= link_to 'New Campaign', new_campaign_path %>
          </li>
          <li>
            <%= link_to 'Campaign Lists', campaigns_path %>
          </li>
          <li>
            <%= link_to 'Stats', campaigns_path %>
          </li>
        </ul>
        <li>
          <a href="#">
            <i class="fa fa-line-chart fa-lg"></i> Statistics
          </a>
        </li>

        <li data-toggle="collapse" data-target="#share" class="collapsed">
          <a href="javascript:void(0)">
            <i class="fa fa-share-alt fa-lg"></i> Social Share <span class="arrow"></span>
          </a>
        </li>
        <li>
          <ul class="sub-menu collapse <%= active_collapse(['social_campaigns']) %>" id="share">
            <li>
              <%= link_to 'New Social Campaign', new_social_campaign_path %>
            </li>
            <li>
              <%= link_to ' Social Campaign Lists', social_campaigns_path %>
            </li>
            <li>
              <%= link_to 'Stats', social_campaigns_path %>
            </li>
          </ul>
        </li>
        <li>
          <a href="<%= destroy_user_session_path %>" data-method="delete">
            <i class="fa fa-sign-out fa-lg"></i> Logout
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>