config/routes.rb
Rails.application.routes.draw do
  get 'mail_stores/template'

  devise_for :users, controllers: {
                       sessions: 'users/sessions',
                       passwords: 'users/passwords',
                       registrations: 'users/registrations',
                       unlocks: 'users/unlocks',
                       confirmations: 'users/confirmations',
                       invitations: 'users/invitations'
                   }
  get 'home/index'
  get :email_open, to: 'home#email_open'

  root 'home#index'

  resources :mail_stores
  resources :campaigns do
    resources :recipients do
      get :open
    end
    get :email_view
    post :publish
  end

  namespace :webhook do
    post :delivered, to: 'email_campaign#delivered'
    post :opened, to: 'email_campaign#opened'
    post :clicked, to: 'email_campaign#clicked'
    post :bounced, to: 'email_campaign#bounced'
    post :spamed, to: 'email_campaign#spamed'
  end

  resources :social_campaigns do
    get :share, on: :member
  end

end

app/models/social_campaign.rb
class SocialCampaign < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :image, ImageUploader
end

app/controllers/social_campaigns_controller.rb
class SocialCampaignsController < ApplicationController
  protect_from_forgery with: :exception

  def index
    @social_campaigns = SocialCampaign.all
  end

  def new
    @social_campaign = SocialCampaign.new
  end

  def create
    @social_campaign = SocialCampaign.new(campaign_params)
    respond_to do |format|
      format.html do
        if @social_campaign.save
          redirect_to @social_campaign
        else
          render :new
        end
      end
    end
  end

  def show
    @social_campaign = SocialCampaign.friendly.find(params[:id])
  end


  def edit
    @social_campaign = SocialCampaign.friendly.find(params[:id])
  end

  def update
    @social_campaign = SocialCampaign.friendly.find(params[:id])
    respond_to do |format|
      format.html do
        unless @social_campaign.update_attributes(campaign_params)
          flash[:error] = 'Unable to update campaign. Please try again!'
        end
        redirect_to @social_campaign
      end
    end
  end


  def destroy
    @social_campaign = SocialCampaign.friendly.find(params[:id])
    respond_to do |format|
      format.html do
        unless @social_campaign.delete
          flash[:error] = 'Unable to delete campaign. Please try again!'
        end
        redirect_to social_campaigns_path
      end
    end
  end

  def share
    @social_campaign = SocialCampaign.friendly.find(params[:id])
  end


  private

  def campaign_params
    params.require(:social_campaign).permit!
  end

end

app/helpers/social_campaigns_helper.rb
module SocialCampaignsHelper
end

app/views/social_campaigns/_form.html.erb
<div id="content">

  <h1>Social Campaign </h1>
  <%= form_for @social_campaign do |f| %>
      <div class="clearfix">
        <div class="form-group col-lg-12 mt15">
          <div class="row">
            <div class="col-sm-6">
              <%= f.label :title, 'Title*' %>
              <%= f.text_field :title, placeholder: 'Campaign title', class: 'form-control' %>
            </div>
            <div class="col-sm-6">
              <%= f.label :link, 'Subject*', class: '' %>
              <%= f.text_field :link, placeholder: 'Campaign link', class: 'form-control' %>
            </div>
          </div>
        </div>

        <div class="form-group col-sm-12 mt15">
          <%= f.label :description, 'Description*' %>
          <%= f.text_area :description, placeholder: 'Type your description', class: 'form-control', rows: '8' %>
        </div>

        <div class="fileselector pull-left">
          <label class="btn btn-default" for="upload-file-selector">
            <%= f.file_field :image, class: 'fa fa-paperclip', id: 'upload-file-selector' %>
            <i class="fa fa-upload"></i>Upload Attachment
          </label>
        </div>

        <div class="form-group col-md-12 mt15">
          <%= f.submit @social_campaign.new_record? ? 'Create Campaign' : 'Update Campaign', class: 'btn btn-info submit-btn pull-right' %>
        </div>
      </div>
  <% end %>
</div>

<script type="text/javascript">
    function jqloader() {
//        tinymce.init({
//            selector: 'textarea',
//            height: 250,
//            theme: 'modern',
//            plugins: [
//                'advlist autolink lists link image charmap print preview hr anchor pagebreak',
//                'searchreplace wordcount visualblocks visualchars code fullscreen',
//                'insertdatetime media nonbreaking save table contextmenu directionality',
//                'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc help'
//            ],
//            toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
//            toolbar2: 'print preview media | forecolor backcolor emoticons | imageupload | codesample help',
//            image_advtab: true,
//            statusbar: false,
//            setup: function (editor) {
//                var inp = $('<input id="tinymce-uploader" type="file" name="pic" accept="image/*" style="display:none">');
//                $(editor.getElement()).parent().append(inp);
//
//                inp.on("change", function () {
//                    var input = inp.get(0);
//                    var file = input.files[0];
//                    var fr = new FileReader();
//                    fr.onload = function () {
//                        var img = new Image();
//                        img.src = fr.result;
//                        editor.insertContent('<img src="' + img.src + '"/>');
//                        inp.val('');
//                    };
//                    fr.readAsDataURL(file);
//                });
//
//                editor.addButton('imageupload', {
//                    text: "Image",
//                    icon: false,
//                    onclick: function (e) {
//                        inp.trigger('click');
//                    }
//                });
//            }
//        });
    }
    $(document).on("turbolinks:load", jqloader);
</script>

app/views/social_campaigns/_social_campaign.html.erb
<tr data-status="pagado">
  <td>
    <div class="ckbox">
      <input type="checkbox" id="checkbox1">
      <label for="checkbox1"></label>
    </div>
  </td>
  <td>
    <a href="javascript:;" class="star">
      <i class="glyphicon glyphicon-star"></i>
    </a>
  </td>
  <td>
    <div class="media">
      <a href="#" class="pull-left">
        <%= image_tag social_campaign.image, width: 100 %>
      </a>

      <div class="xxxx">
        <span class="media-meta pull-right"><%= social_campaign.created_at.strftime('%b %d, %Y') %></span>
        <h4 class="title">
          <%= social_campaign.link %> <br/>
          <span class="pull-right pagado">
            <%= link_to 'Share', share_social_campaign_path(social_campaign) %> |
            <%= link_to 'View', social_campaign_path(social_campaign) %> |
            <%= link_to 'Edit', edit_social_campaign_path(social_campaign) %> |
            <%= link_to 'Delete', social_campaign_path(social_campaign), method: :delete %>
          </span>
        </h4>

        <p class="summary">
          <%= raw social_campaign.description %>
        </p>
      </div>
    </div>
  </td>
</tr>

app/views/social_campaigns/edit.html.erb
<div class="notice notice-info">
  <strong>Campaign:</strong> Edit social campaign
</div>

<%= render 'form' %>

app/views/social_campaigns/index.html.erb
<div class="notice notice-info">
  <strong>Campaign:</strong> My Social Campaign
</div>

<div id="campaign-list">

  <section class="content">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="table-container">
          <table class="table table-filter">
            <tbody>
            <% @social_campaigns.each do |social_campaign| %>
                <%= render social_campaign %>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>

</div>

app/views/social_campaigns/new.html.erb
<div class="notice notice-info">
  <strong>Campaign:</strong> Create new social campaign
</div>

<%= render 'form' %>

app/views/social_campaigns/share.html.erb
<% content_for :head do %>
  <meta property="og:url" content="<%= @social_campaign.link %>">
  <meta name="twitter:url" content="<%= @social_campaign.link %>">
  <meta property="og:title" content="<%= @social_campaign.link %>">
  <meta name="twitter:title" content="<%= @social_campaign.link %>">
  <meta property="og:description" content="<%= @social_campaign.description %>">
  <meta name="twitter:description" content="<%= @social_campaign.description %>">

  <meta property="og:image" content="<%#= root_url + @social_campaign.image_url %>">
  <meta name="twitter:image" content="<%#=  root_url + @social_campaign.image_url %>">
    <meta property="og:image:width" content="450"/>
    <meta property="og:image:height" content="298"/>
<% end %>

<div class="notice notice-info">
  <strong>Campaign:</strong> Campaign details #<%= @social_campaign.id %>
  <%= link_to edit_campaign_path(@social_campaign) do %>
      <i class="fa fa-pencil-square-o"></i>
  <% end %>
</div>

<div id="content">
  <h1> <%= @social_campaign.link %> </h1>


  <div class="panel panel-primary">
    <div class="panel-heading"> Share Campaign</div>
    <div class="panel-body">
      <%#= social_share_button_tag(@social_campaign.link, :url => @social_campaign.link, :image => root_url + @social_campaign.image_url, desc: @social_campaign.description, via: "MyTwitterName") %>
      <%= social_share_button_tag(@social_campaign.link) %>
    </div>
  </div>


  <h3> <%= raw @social_campaign.description %> </h3>

</div>

app/views/social_campaigns/show.html.erb
<div class="notice notice-info">
  <strong>Campaign:</strong> Campaign details #<%= @social_campaign.id %>
  <%= link_to edit_social_campaign_path(@social_campaign) do %>
      <i class="fa fa-pencil-square-o"></i>
  <% end %>
</div>

<div id="content">
  <h1> <%= @social_campaign.link %> </h1>

  <div class="panel panel-info">
    <div class="panel-heading"> Campaign Statistics</div>
    <div class="panel-body">
      <div class="row">
        <div class="col col-sm-6">
          <h4>Campaign Stats:</h4>
          FaceBook Share
          <span class="pull-right strong"><%= get_fb_share("http://02bf948e.ngrok.io#{share_social_campaign_url(@social_campaign)}") %></span>

          <div class="progresss">
            <!--<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100" style="width:15%">15%</div>-->
          </div>


          Twitter Share <span class="pull-right strong"><%#= get_twitter_share(@social_campaign.link) %></span>

          <div class="progresss">
            <!--<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100" style="width:15%">15%</div>-->
          </div>

          Linked In Share
          <span class="pull-right strong"><%= get_linkedIn_share(share_social_campaign_url(@social_campaign)) %></span>

          <div class="progresss">
            <!--<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100" style="width:15%">15%</div>-->
          </div>

          Google+ Share
          <span class="pull-right strong"><%= google_plus_share(share_social_campaign_url(@social_campaign)) %></span>
        </div>

        <div class="col-sm-6">
          <div id="damage-graph">

          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="panel panel-primary">
    <div class="panel-heading"> Share Campaign</div>
    <div class="panel-body">
      <%= social_share_button_tag(@social_campaign.link, :url => @social_campaign.link, :image => (root_url + @social_campaign.image_url if @social_campaign.image.present?), desc: "The summary of page", via: "MyTwitterName") %>
    </div>
  </div>


  <a href="https://www.facebook.com/dialog/share?app_id=145634995501895&display=popup&href=http://02bf948e.ngrok.io<%= social_campaign_path(@social_campaign) %>&redirect_uri=https%3A%2F%2Fdevelopers.facebook.com%2Ftools%2Fexplorer">
    FB </a>


  <h3> <%= raw @social_campaign.description %> </h3>

</div>

<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=599bbbcfa3155100110e71fc&product=inline-share-buttons"></script>

<script type="text/javascript">
    $(function () {
        $('#recipients').tokenfield();

        $('.send-recipient-btn').click(function (e) {
            e.preventDefault();
            element = $(this);
            form = element.parents('form');
            $.ajax({
                type: 'post',
                url: form.attr('action'),
                data: form.serialize(),
                beforeSend: function () {
                    element.val('Sending...');
                },
                success: function (res) {
                    alert("Campaign sent to " + res.total + " recipient");
                    element.val('Send Campaign');
                    $('#recipients').tokenfield('setTokens', []);
                }
            })
        });
    });

    $(function () {

        $(document).ready(function () {

            // Build the chart
            $('#damage-graph').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    type: 'pie'
                },
                title: {
                    text: 'Category Wise Expense Graph'
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.name}</b>: {point.y}',
                            style: {
                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                            }
                        }
                    }
                },
                series: [{
                    name: 'Category',
                    colorByPoint: true,
                    data: [
                        {
                            name: "FaceBook",
                            y: <%= get_fb_share(share_social_campaign_url(@social_campaign)) %>
                        },
                        {
                            name: "Linkedin",
                            y: <%= get_linkedIn_share(share_social_campaign_url(@social_campaign)) %>
                        },

                        {
                            name: "Google+",
                            y: <%= google_plus_share(share_social_campaign_url(@social_campaign)) %>
                        }
                    ]
                }]
            });
        });
    });
</script>