config/routes.rb
Rails.application.routes.draw do
  get 'mail_stores/template'

  devise_for :users, controllers: {
                       sessions: 'users/sessions',
                       passwords: 'users/passwords',
                       registrations: 'users/registrations',
                       unlocks: 'users/unlocks',
                       confirmations: 'users/confirmations',
                       invitations: 'users/invitations'
                   }
  get 'home/index'
  get :email_open, to: 'home#email_open'

  root 'home#index'

  resources :mail_stores
  resources :campaigns do
    resources :recipients do
      get :open
    end
    get :email_view
    post :publish
  end

  namespace :webhook do
    post :delivered, to: 'email_campaign#delivered'
    post :opened, to: 'email_campaign#opened'
    post :clicked, to: 'email_campaign#clicked'
    post :bounced, to: 'email_campaign#bounced'
    post :spamed, to: 'email_campaign#spamed'
  end

  resources :social_campaigns do
    get :share, on: :member
  end

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :title, :subject, :template
  has_many :recipients

  def publish(recipients)
    recipients.each do |email|
      begin
        recipient = self.recipients.create(email: email)
        begin
          UserMailer.send_campaign(recipient).deliver
        rescue Exception => ex
          p ex.message
          p "Error for sending email"
          recipient.update_attribute(:status, false)
        end
      rescue Exception => e
        p e.message
      end
    end
  end

  def rate
    (total_sent.to_f / total_recipient.to_f) * 100
  end

  def total_recipient
    recipients.count
  end

  def total_sent
    recipients.where(status: true).count
  end

  def total_failed
    recipients.where(status: false).count
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  protect_from_forgery with: :exception
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @campaigns = Campaign.all
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(campaign_params)
    respond_to do |format|
      format.html do
        if @campaign.save
          redirect_to @campaign
        else
          render :new
        end
      end
    end
  end

  def show

  end

  def edit

  end

  def update
    respond_to do |format|
      format.html do
        unless @campaign.update_attributes(campaign_params)
          flash[:error] = 'Unable to update campaign. Please try again!'
        end
        redirect_to @campaign
      end
    end
  end

  def destroy
    respond_to do |format|
      format.html do
        unless @campaign.delete
          flash[:error] = 'Unable to delete campaign. Please try again!'
        end
        redirect_to campaigns_path
      end
    end
  end

  def publish
    campaign = Campaign.friendly.find(params[:campaign_id])
    recipients = params['recipients']
    recipients = recipients.split(',').collect { |email| validate_recipient(email) }.compact
    campaign.publish(recipients)
    respond_to do |format|
      format.json {
        render json: {total: recipients.length}
      }
    end
  end

  def email_view
    @campaign = Campaign.friendly.find(params[:campaign_id])
    render layout: 'mailer'
  end

  private

  def set_campaign
    @campaign = Campaign.friendly.find(params[:id])
    unless @campaign.present?
      render action: 404
    end
  end

  def campaign_params
    params.require(:campaign).permit!
  end

  def validate_recipient(email)
    regex = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    email = email.strip
    email =~ regex ? email : nil
  end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_campaign.html.erb
<tr data-status="pagado">
  <td>
    <div class="ckbox">
      <input type="checkbox" id="checkbox1">
      <label for="checkbox1"></label>
    </div>
  </td>
  <td>
    <a href="javascript:;" class="star">
      <i class="glyphicon glyphicon-star"></i>
    </a>
  </td>
  <td>
    <div class="media">
      <a href="#" class="pull-left">
        <img src="https://s3.amazonaws.com/uifaces/faces/twitter/fffabs/128.jpg" class="media-photo">
      </a>

      <div class="xxxx">
        <span class="media-meta pull-right"><%= campaign.created_at.strftime('%b %d, %Y') %></span>
        <h4 class="title">
          <%= campaign.title %> <br/>
          <span class="pull-right pagado">
            <%= link_to campaign_recipients_path(campaign) do %>
             Recipients(<%= campaign.recipients.count %>)
            <% end %> |
            <%= link_to 'View', campaign_path(campaign) %> |
            <%= link_to 'Edit', edit_campaign_path(campaign) %> |
            <%= link_to 'Delete', campaign_path(campaign), method: :delete %>
          </span>
        </h4>

        <p class="summary">
          <%= campaign.subject %>
        </p>
      </div>
    </div>
  </td>
</tr>

app/views/campaigns/_form.html.erb
<div id="content">

  <h1>Campaign </h1>
  <%= form_for @campaign do |f| %>
      <div class="clearfix">
        <div class="form-group col-sm-6 mt15">
          <%= f.label :subject, 'Subject*', class: '' %>
          <%= f.text_field :subject, placeholder: 'What would you like to talk about?', required: true, class: 'form-control' %>
        </div>

        <div class="form-group col-sm-6 mt15">
          <%= f.label :title, 'Title*' %>
          <%= f.text_field :title, placeholder: 'Type your title', required: true, class: 'form-control' %>
        </div>

        <div class="fileselector pull-right">
          <label class="btn btn-default" for="upload-file-selector">
            <%= f.file_field :attachment, class: 'fa fa-paperclip', id: 'upload-file-selector' %>
            <i class="fa fa-upload"></i>Upload Attachment
          </label>
        </div>

        <div class="col-lg-12">
          <%= f.label :template, 'Template*' %>
          <%= f.text_area :template, placeholder: 'Your message here', class: 'form-control' %>
        </div>

        <div class="form-group col-md-12 mt15">
          <%= f.submit @campaign.new_record? ? 'Create Campaign' : 'Update Campaign', class: 'btn btn-info submit-btn pull-right' %>
        </div>
      </div>
  <% end %>
</div>

<script type="text/javascript">
    function jqloader() {
        tinymce.init({
            selector: 'textarea',
            height: 500,
            theme: 'modern',
            plugins: [
                'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc help'
            ],
            toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            toolbar2: 'print preview media | forecolor backcolor emoticons | imageupload | codesample help',
            image_advtab: true,
            statusbar: false,
            setup: function (editor) {
                var inp = $('<input id="tinymce-uploader" type="file" name="pic" accept="image/*" style="display:none">');
                $(editor.getElement()).parent().append(inp);

                inp.on("change", function () {
                    var input = inp.get(0);
                    var file = input.files[0];
                    var fr = new FileReader();
                    fr.onload = function () {
                        var img = new Image();
                        img.src = fr.result;
                        editor.insertContent('<img src="' + img.src + '"/>');
                        inp.val('');
                    };
                    fr.readAsDataURL(file);
                });

                editor.addButton('imageupload', {
                    text: "Image",
                    icon: false,
                    onclick: function (e) {
                        inp.trigger('click');
                    }
                });
            }
        });
    }
    $(document).on("turbolinks:load", jqloader);
</script>

app/views/campaigns/edit.html.erb
<div class="notice notice-info">
  <strong>Campaign:</strong> Edit campaign
</div>

<%= render 'form' %>

app/views/campaigns/email_view.html.erb
<%= raw @campaign.template %>

app/views/campaigns/index.html.erb
<div class="notice notice-info">
  <strong>Campaign:</strong> My Campaign
</div>

<div id="campaign-list">

  <section class="content">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="table-container">
          <table class="table table-filter">
            <tbody>
            <% @campaigns.each do |campaign| %>
                <%= render campaign %>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>

</div>

app/views/campaigns/new.html.erb
<div class="notice notice-info">
  <strong>Campaign:</strong> Create new campaign
</div>

<%= render 'form' %>

app/views/campaigns/show.html.erb
<div class="notice notice-info">
  <strong>Campaign:</strong> Campaign details #<%= @campaign.id %>
  <%= link_to edit_campaign_path(@campaign) do %>
      <i class="fa fa-pencil-square-o"></i>
  <% end %>
</div>

<div id="content">
  <h1> <%= @campaign.title %> </h1>

  <h3> <%= @campaign.subject %> </h3>
  <iframe src="<%= campaign_email_view_path(@campaign.id) %>" width="100%" height="100%">

  </iframe>

  <div class="mb10">
    <%= link_to campaign_recipients_path(@campaign) do %>
        <i class="fa fa-users"></i> Recipients
    <% end %>
    |
    <%= link_to campaign_recipients_path(@campaign) do %>
        <i class="fa fa-line-chart"></i> Statistics
    <% end %>
  </div>

  <div class="panel panel-info">
    <div class="panel-heading"> Campaign Statistics</div>
    <div class="panel-body">
      <div class="row">
        <div class="col col-sm-6">
          <h4>Campaign Stats:</h4>
          Campaign Rate <span class="pull-right strong"><%= @campaign.rate %>%</span>

          <div class="progress">
            <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100" style="width:<%= @campaign.rate %>%">
              <%= @campaign.rate %>%
            </div>
          </div>

          <%= @campaign.total_sent %> Recipient Sent Target(100)
          <span class="pull-right strong"><%= @campaign.total_sent %>%</span>

          <div class="progress">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width:<%= @campaign.total_sent %>%">
              <%= @campaign.total_sent %>%
            </div>
          </div>

          <%= @campaign.total_failed %> Recipient Failed
          <span class="pull-right strong"><%= @campaign.total_failed %></span>

          <div class="progress mb10">
            <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="8" aria-valuemin="0" aria-valuemax="100" style="width:<%= @campaign.total_failed %>%">
              <%= @campaign.total_failed %>%
            </div>
          </div>
        </div>

        <div class="col col-sm-6">
          <h4>Recipient Stats:</h4>
          Open Rate <span class="pull-right strong">+ 45%</span>

          <div class="progress">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width:45%">45%</div>
          </div>

          Click Rate<span class="pull-right strong">+ 57%</span>

          <div class="progress">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="57" aria-valuemin="0" aria-valuemax="100" style="width:57%">57%</div>
          </div>

          Reopen <span class="pull-right strong">+ 25%</span>

          <div class="progress">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width:25%">25%</div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="panel panel-primary">
    <div class="panel-heading"> Send Campaign</div>
    <div class="panel-body">
      <%= form_tag campaign_publish_path(@campaign, format: 'json'), id: 'send-recipient' do %>
          <%= text_field_tag :recipients, '', placeholder: "Recipients or Upload" %>

          <div class="fileselector ml0 clearfix">
            <label class="btn btn-default pull-left" for="upload-file-selector">
              <%= file_field_tag :file, id: 'upload-file-selector', class: 'pull-left', onChange: "loadRecipient('#recipients', event)" %>
              <i class="fa fa-upload"></i>Upload Emails
            </label>
          </div>
          <%= submit_tag 'Send Campaign', class: 'btn btn-success pull-right send-recipient-btn' %>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(function () {
        $('#recipients').tokenfield({
            createTokensOnBlur: true
        });

        $('.send-recipient-btn').click(function (e) {
            e.preventDefault();
            element = $(this);
            form = element.parents('form');
            $.ajax({
                type: 'post',
                url: form.attr('action'),
                data: form.serialize(),
                beforeSend: function () {
                    element.val('Sending...');
                },
                success: function (res) {
                    alert("Campaign sent to " + res.total + " recipient");
                    element.val('Send Campaign');
                    $('#recipients').tokenfield('setTokens', []);
                }
            })
        });
    });
</script>